-- Migration: Enrich Programming Guides with Narrative Content (Agent 3E)
-- Sourced from: Ford_BCM_Security_Bypass_Research.txt, GM_Global_B_Key_Programming_Research.txt, etc.

BEGIN TRANSACTION;

-- Update Ford 2021+ Guide with "Double Honk" and "Power Isolation" Logic
INSERT OR REPLACE INTO programming_guides (title, make, model, year_start, year_end, content, category)
VALUES ('Ford 2021+ Next-Gen Security (Locked BCM)', 'Ford', 'F-150, Bronco, Mach-E', 2021, 2025,
'# Ford 2021+ "Locked BCM" & Active Theft Guide

## 🎭 The "Locked BCM" Myth
In Ford’s FNV2 architecture, a "Locked BCM" is not a hardware failure but a **state-dependent firewall rule**. When the Active Theft system is armed, the Gateway Module (GWM) blocks all security access commands (0x27) from the OBD port.

## 🎺 The "Double Honk" Diagnostic
If you attempt to program a key and the vehicle responds with a **Double Honk**, the BCM is signaling that it received the request but rejected it because the security conditions (Alarm Disarmed) were not met. This is a definitive indicator that a physical bypass is required.

## ⚡ The Physics of Power Isolation
To bypass the lockout, you must use a **12-Pin Bypass Cable** with external battery clamps.
1. **Reset**: Disconnect the vehicle battery to clear the "Panic" state.
2. **Isolate**: Power your tool/VCI via the external clamps.
3. **Stealth Boot**: Reconnect the battery. The BCM will boot up with an established diagnostic session already active, often bypassing the initial alarm trigger.

## 📡 902 MHz Shift
Most modern Ford trucks have moved to the **902 MHz** band (FCC ID: M3N-A2C931426). Universal fobs often struggle with stability here; OEM or hardware-optimized solutions like Xhorse XM38 are recommended.', 
'TECHNICAL_DEEP_DIVE');

-- Update GM Global B Guide with "12th Digit Rule"
INSERT OR REPLACE INTO programming_guides (title, make, model, year_start, year_end, content, category)
VALUES ('GM Global B (VIP) Identification and Tokens', 'Chevrolet, GMC, Cadillac', 'Various (Global B)', 2020, 2025,
'# GM Global B (VIP) Programming Guide

## 🔢 The "12th Digit Rule" (2022 Trucks)
For the 2022 Silverado/Sierra, the 10th and 11th VIN digits are insufficient.
- **Digit 12 <= 4**: Legacy Global A (Limited model). OBD programming is open.
- **Digit 12 >= 5**: Next-Gen Global B (Refresh model). Requires CAN FD and Server Tokens.

## 🔑 The 24-Digit Token Handshake
Global B has abolished static PIN codes. Every programming session requires a **unique 24-digit token** calculated by GM servers. This enforces a strictly "online-only" workflow. 

## ⚠️ The Timeout Window
Once a "Challenge Seed" is generated by the BCM, there is a narrow window (often < 2 minutes) to provide the 24-digit response. Ensure stable Wi-Fi/LTE before initiating the session to prevent timeout-induced lockouts.', 
'TECHNICAL_DEEP_DIVE');

-- Update Legacy Domestic (Passlock/SKIM)
INSERT OR REPLACE INTO programming_guides (title, make, model, year_start, year_end, content, category)
VALUES ('Legacy Domestic (2000-2010) Security Architecture', 'Chrysler, GM', 'Legacy Platforms', 2000, 2010,
'# Legacy Domestic Security: PCI vs CAN

## 🕒 The 30-Minute Relearn (GM Passlock)
Passlock I/II systems (Impala, Malibu < 2005) rely on an analog voltage reference. Digital tools cannot "bypass" the wait. The **30-minute manual relearn** (3 cycles of 10 minutes) is a hard-coded BCM timeout that must be respected. Maintain 13.5V+ with a maintainer to prevent session abort.

## 🧵 The SKIM EEPROM Solution (Chrysler PCI)
On 2000-2004 Chrysler vehicles (PCI Bus), the PIN code is often not broadcast to the OBD port. 
- **The Fail**: "Failed to Communicate" via OBD.
- **The Fix**: Remove the SKIM module from the column. Read the **95040 or 24C02 EEPROM** chip directly to extract the 4-digit PIN. This is the only definitive path for All Keys Lost on early WJ/KJ platforms.', 
'TECHNICAL_DEEP_DIVE');

COMMIT;
