-- Migration to add AI Insights table

CREATE TABLE insights (
    id TEXT PRIMARY KEY,
    user_id TEXT, -- 'global' or specific user ID
    content TEXT, -- The markdown report generated by AI
    recommendations JSON, -- Structured array of recommended ASINs/products
    created_at INTEGER
);

CREATE INDEX idx_insights_created_at ON insights(created_at);
CREATE INDEX idx_insights_user ON insights(user_id);
