#!/usr/bin/env python3
"""
Update aks_products.fcc_id in D1 to have full multi-FCC strings from source JSON.
This fixes the issue where only the first FCC ID was stored during import.

Usage: python3 scripts/update_multi_fcc_ids.py [--dry-run]
"""

import json
from pathlib import Path

SOURCE_JSON = Path("data/imports/aks_products.json")
OUTPUT_SQL = Path("data/migrations/update_multi_fcc_ids.sql")

def escape_sql(val):
    """Escape value for SQL."""
    if val is None:
        return "NULL"
    val = str(val).replace("'", "''")
    return f"'{val}'"

def main():
    print("Loading source JSON...")
    with open(SOURCE_JSON) as f:
        data = json.load(f)
    
    products = data.get('products', [])
    print(f"Loaded {len(products)} products")
    
    # Find products with multi-FCC IDs (containing newlines)
    updates = []
    for product in products:
        fcc_id = product.get('fcc_id', '')
        item_num = product.get('item_num')
        
        if not item_num or not fcc_id:
            continue
        
        # Check if has multiple FCC IDs
        if '\n' in fcc_id:
            # Replace newlines with spaces for cleaner storage and LIKE matching
            clean_fcc = fcc_id.replace('\n', ' ').strip()
            updates.append({
                'item_id': item_num,
                'fcc_id': clean_fcc
            })
    
    print(f"Found {len(updates)} products with multi-FCC IDs")
    
    # Generate SQL
    sql_lines = [
        "-- Update aks_products with full multi-FCC strings",
        "-- Generated by update_multi_fcc_ids.py",
        ""
    ]
    
    for u in updates:
        sql = f"UPDATE aks_products SET fcc_id = {escape_sql(u['fcc_id'])} WHERE item_id = {u['item_id']};"
        sql_lines.append(sql)
    
    # Write SQL file
    OUTPUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_SQL, 'w') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"\nGenerated: {OUTPUT_SQL}")
    print(f"Contains {len(updates)} UPDATE statements")
    print("\nTo apply, run:")
    print(f"  npx wrangler d1 execute locksmith-db --remote --file={OUTPUT_SQL}")

if __name__ == "__main__":
    main()
